version: "3"

services:
  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: mysql:5.7
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "3066:3306"
    networks:
      - neuralwp-network

  php:
    build:
      context: install/php-fpm
      args:
        PHP_VER: $PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      - ./:/var/www/html
    networks:
      - neuralwp-network
    extra_hosts:
      - "${PROJECT_BASE_URL}:host-gateway"
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    image: nginx:alpine
    working_dir: /var/www/html/
    depends_on:
      - php
    volumes:
      - ./:/var/www/html/
      - ./install/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./install/php-fpm/error.log:/var/log/php/neuralwp.loc.error.log
      - ./install/nginx/access.log:/var/log/nginx/neuralwp.loc.access.log
    ports:
      - "80:80"
      - "443:443"
    networks:
      - neuralwp-network

  tests:
    build:
      context: install/tests
      args:
        EXT_USER_ID: $EXT_USER_ID
    environment:
      DB_HOST: $DB_HOST
      DB_ROOT_USER: $DB_ROOT_USER
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      DB_TESTS_NAME: $DB_TESTS_NAME
      EXT_USER_ID: $EXT_USER_ID
    container_name: "${PROJECT_NAME}_tests"
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    links:
      - mysql
    networks:
      - neuralwp-network

networks:
  neuralwp-network:
    driver: bridge
